default: &default
  adapter: postgresql
  encoding: unicode
  username: wendellopes
  password: w2n1b1b2
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bank_nobi_development

test:
  <<: *default
  database: bank_nobi_test

production:
  <<: *default
  database: bank_nobi_production
  username: bank_nobi
